<?php
/**
 * Shows add user form
 *
 * @author     LMV <luis.montealegre@mandragora-web-systems.com>
 * @copyright  Mandrágora Web-Based Systems 2010
 * @version    SVN: $Id$
 */
?>
<?php
$title = $this->translate('user.action.create');
$this->headTitle($title);
$this->bundleLink()
     ->appendStylesheet($this->baseUrl('/styles/breadcrumbs.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/skins/breadcrumbs.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/forms.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/skins/forms.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/jquery/plugins/rte.css'), 'screen, projection', false, array('charset' => 'utf-8'));
$this->jQuery()
     ->addJavascriptFile($this->baseUrl('/scripts/jquery/plugins/jquery.validate.js'))
     ->addJavascriptFile($this->baseUrl('/scripts/edeco/pages/user/class.detail.js'));
$onLoad = sprintf(
    'var page = new Edeco.Pages.User.Detail();
    page.init();');
$this->jQuery()->addOnLoad($onLoad);
?>
<h1><?php echo $title ?></h1>
<div class="span-6">
    <div class="actions">
        <ul class="actions-container">
            <?php $actions = array('user.action.list' => array($this->translate('page') => 1)) ?>
            <?php echo $this->partial('navigation/_actions.phtml', array('pages' => $this->actions, 'actions' => $actions, 'decorator' => 'li')) ?>
        </ul>
    </div>
</div>
<div class="span-18 last">
    <?php echo $this->userForm ?>
</div>