<?php
/**
 * Show property information
 *
 * @author     LMV <luis.montealegre@mandragora-web-systems.com>
 * @copyright  Mandrágora Web-Based Systems 2010
 * @version    SVN: $Id$
 */
?>
<?php
$title = $this->translate('user.action.show');
$this->headTitle($title);
$this->bundleLink()
     ->appendStylesheet($this->baseUrl('/styles/breadcrumbs.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/skins/breadcrumbs.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/tables.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/skins/tables.css'), 'screen, projection', false, array('charset' => 'utf-8'));
$this->jQuery()
     ->addJavascriptFile($this->baseUrl('/scripts/jquery/plugins/jquery.confirm.js'))
     ->addJavascriptFile($this->baseUrl('/scripts/edeco/pages/user/class.show.js'));
$this->jQuery()->addOnLoad(
    'var page = new Edeco.Pages.User.Show();
    page.init();'
);

?>
<h1><?php echo $this->translate('user.action.show') ?></h1>
<div class="clearfix">
    <div class="span-6">
        <div class="actions">
            <ul class="actions-container">
                <?php
                $params = array($this->translate('username') => $this->user->username);
                $actions = array(
                    'user.action.list' => array($this->translate('page') => 1),
                    'user.action.create' => array(),
                    'user.action.edit' => $params,
                    'user.action.show' => $params,
                    'user.action.delete' => $params,
                );
                echo $this->partial(
                    'navigation/_actions.phtml',
                    array(
                        'pages' => $this->actions,
                        'actions' => $actions,
                        'decorator' => 'li'
                    )
                );
                ?>
            </ul>
        </div>
    </div>
    <div class="span-18 last">
        <?php echo $this->partial('partials/flash-messages.phtml', array('messages' => $this->messages)) ?>
        <?php echo $this->partial('partials/model.phtml', array('model' => $this->user->toArray(), 'prefix' => 'user.field.')) ?>
    </div>
</div>