<?php
/**
 * Shows error page
 *
 * @author     LMV <luis.montealegre@mandragora-web-systems.com>
 * @copyright  Mandrágora Web-Based Systems 2010
 * @version    SVN: $Id$
 */
?>
<?php
$this->bundleLink()
     ->appendStylesheet($this->baseUrl('/styles/breadcrumbs.css'), 'screen, projection')
     ->appendStylesheet($this->baseUrl('/styles/skins/breadcrumbs.css'), 'screen, projection');
?>
<div class="grid_10 push_1 alpha clearfix">
    <h1>Ha ocurrido un error</h1>
    <?php if ('production' !== APPLICATION_ENV) : ?>
        <?php $this->headTitle('Ha ocurrido un error') ?>
        <h2>Información de la excepción:</h2>
        <p>
            <strong>Excepción: </strong><?php echo get_class($this->exception) ?>
            <br />
            <strong>Mensaje: </strong><?php echo $this->exception->getMessage() ?>
        </p>
        <h2>Traza:</h2>
        <pre class="trace error"><code><?php echo $this->exception->getTraceAsString() ?></code></pre>
        <h3>Parámetros de la solicitud:</h3>
        <pre class="trace error"><code><?php echo var_export($this->request->getParams(), true) ?></code></pre>
        <h3>IP del cliente:</h3>
        <pre class="error"><code><?php echo $this->request->getClientIp() ?></code></pre>
        <h3>Agente de usuario:</h3>
        <pre class="error"><code><?php echo $this->request->getServer('HTTP_USER_AGENT') ?></code></pre>
        <h3>URI solicitada:</h3>
        <pre class="error"><code><?php echo $this->request->getServer('REQUEST_URI') ?></code></pre>
    <?php else : ?>
        <?php $this->headTitle($this->message) ?>
        <p><?php echo $this->message ?></p>
    <?php endif ?>
</div>