<?php
/**
 * Shows about page
 *
 * @author    MMS <meri.michimani@mandragora-web-systems.com>
 * @author    LMV <luis.montealegre@mandragora-web-systems.com>
 * @copyright Mandrágora Web-Based Systems
 * @version   SVN: $Id$
 */
?>
<?php $this->headTitle('Declaracion de accesibilidad') ?>
<?php echo $this->render('default/_side-content.phtml') ?>
<div class="span-18 last">
<h1>Declaraciones de Accesibilidad</h1>
    <p>
        Esta es la declaración de accesibilidad oficial de Edificaciones y Desarrollos
        Comerciales de México. Si usted tiene alguna pregunta o comentario sientáse
        libre de enviar un correo electrónico a
        <a href="mailto:soporte@mandragora-web-systems.com">soporte@mandragora-web-systems.com</a>
    </p>
</div>
<div class="span-18 last">
    <h2>Teclas de acceso rápido</h2>
    <p>
        La mayoría de los navegadores soportan el acceso a secciones especificas
        de un sitio Web utilizando una  combinación de teclas, a las cuales se
        les connoce como teclas de acceso rápido.
    </p>
    <p>
        Todas las páginas de este sitio definen las siguientes teclas de acceso
        rápido:
    </p>
    <ul>
        <li>Tecla 0: Página de inicio </li>
        <li>Tecla 1: ¿Quienes somos?</li>
        <li>Tecla 2: Objetivos estratégicos</li>
        <li>Tecla 3: Inmuebles</li>
        <li>Tecla 4: Contacto</li>
        <li>Tecla 5: Correo</li>
        <li>Tecla 6: ¿Buscas un local?</li>
    </ul>
    <h3>Como usar los accesos rápidos</h3>
    <p>
        Para un correcto funcionamiento puede que sea necesario que utilice los
        dígitos que se encuentran encima de las letras en su teclado.
    </p>
    <ul>
        <li>Mozilla: Alt + Mayús(Shift) + Tecla</li>
        <li>Internet Explorer: Alt + Tecla de acceso, soltar teclas y presionar Enter</li>
        <li>Opera: Shift + Esc, soltar teclas y elegir opción</li>
        <li>Safari: Alt + opción</li>
        <li>Google Chrome: Alt + opción</li>
    </ul>
    <h2>Estándares de conformidad</h2>
    <ul>
        <li>
            Todas las páginas en este sitio están aprobadas por las guías
            <acronym title="Web Content Accesibility Guidelines (Guias de Accesibilidad para Contenido Web)">WCAG AAA</acronym>
            y cumplen con las especificaciones de nivel 1, 2 y 3 de las guías de
            contenido de accesibilidad web del W3C. En la parte inferior de todas
            las páginas puede verificar que todo el contenido cumple con dichas
            guías.
        </li>
        <li>
            Todas las páginas en este sitio se validan como <acronym title="eXtensible Hypertext Markup Language (Lenguaje Extensible de Marcado de Hipertexto)">XHTML</acronym>
            1.0 estricto. En la parte inferior de todas las páginas puede verificar
            que todo el contenido cumple con el estándar.
        </li>
        <li>
            Todas las páginas en este sitio se validan como <acronym title="Cascading Style Sheets (Hojas de Estilo en Cascada)">CSS2</acronym>. En la parte
            inferior de todas las páginas puede verificar que todo el contenido
            cumple con el estándar.
        </li>
    </ul>
</div>
