<?php
/**
 * Shows about page
 *
 * @author    MMS <meri.michimani@mandragora-web-systems.com>
 * @author    LMV <luis.montealegre@mandragora-web-systems.com>
 * @copyright Mandrágora Web-Based Systems
 * @version   SVN: $Id$
 */
?>
<?php $this->headTitle('Aviso Legal') ?>
<?php echo $this->render('default/_side-content.phtml') ?>
<div class="span-18 last">
<h1>Aviso Legal</h1>
    <p>
        A menos que se especifique de otro modo, todos los materiales  de este
        sitio tienen Copyright &copy; 2010 Edificaciones y Desarrollos
        Comerciales de México. Todos los derechos reservados.
    </p>
    <p>
        El contenido de este sitio Web puede reproducirse y distribuirse en
        formato impreso electrónico sólo si es ofrecido sin costo alguno a los
        beneficios y además se da todo el crédito a Edificaciones y Desarrollos
        Comerciales de México incluyendo una liga al sitio de dirección
        <a href="http://www.edeco.mx">www.edeco.mx</a> en un lugar claramente
        visible. En cualquiera de los dos casos este aviso legal debe permanecer
        intacto.
    </p>
    <p>
        Edificaciones y Desarrollos Comerciales de México nunca venderá,
        prestará, intercambiará, comerciará, o cederá ningún tipo de información
        que usted nos envie, a terceros.
    </p>
    <p>
        Al acceder a este sitio, usted garantiza a Edificaciones y Desarrollos
        Comerciales de México que no usará el sitio web para ningún fin ilegal o
        prohibido en virtud de los presentes avisos y condiciones.
    </p>
    <p>
        Edificaciones y Desarrollos Comerciales de México se reserva también el
        derecho a suspender, o bloquear permanentemente su acceso a este sitio a
        su entera discreción.
    </p>
</div>