<?php
/**
 * Shows form contact page
 *
 * @author    LMV <luis.montealegre@mandragora-web-systems.com>
 * @copyright Mandrágora Web-Based Systems
 * @version   SVN: $Id$
 */
?>
<?php $this->headTitle('Muchas gracias por su confianza') ?>
<?php echo $this->render('default/_side-content.phtml') ?>
<div class="span-18 last">
    <h1 class="two-column">Muchas gracias por su confianza</h1>
    <div class="span-7">
        <p>
            Gracias por confiar en Edificaciones y Desarrollos Comerciales de
            México
        </p>
    </div>
    <div class="span-11 last">
        <img alt="" src="<?php echo $this->baseUrl('/images/confirmation.jpg') ?>" />
    </div>
</div>