<?php
/**
 * Shows address page
 *
 * @author     LNJ <lemuel.nonoal@mandragora-web-systems.com>
 * @author     LMV <luis.montealegre@mandragora-web-systems.com>
 * @copyright  Mandrágora Web-Based Systems 2010
 * @version    SVN: $Id$
 */
?>
<?php
$title = $this->translate('address.action.create');
$this->headTitle($title);
$this->bundleLink()
     ->appendStylesheet($this->baseUrl('/styles/breadcrumbs.css'), 'screen, projection')
     ->appendStylesheet($this->baseUrl('/styles/skins/breadcrumbs.css'), 'screen, projection')
     ->appendStylesheet($this->baseUrl('/styles/forms.css'), 'screen, projection')
     ->appendStylesheet($this->baseUrl('/styles/skins/forms.css'), 'screen, projection')
     ->appendStylesheet($this->baseUrl('/styles/jquery/plugins/rte.css'), 'screen, projection');
$this->jQuery()
     ->addJavascriptFile($this->baseUrl('/scripts/jquery/plugins/jquery.validate.js'))
     ->addJavascriptFile($this->baseUrl('/scripts/jquery/plugins/jquery.rte.js'))
     ->addJavascriptFile($this->baseUrl('/scripts/jquery/plugins/jquery.rtetidy.js'))
     ->addJavascriptFile($this->baseUrl('/scripts/jquery/plugins/validate/method.rte.js'))
     ->addJavascriptFile($this->baseUrl('/scripts/edeco/pages/address/class.detail.js'));
$onload = sprintf(
    'var addressPage = new Edeco.Pages.Address.Detail();
    addressPage.init("%s", "%s", "%s");',
    $this->url(array('controller' => 'city', 'action' => 'search', $this->translate('stateId') => 'stateId'), 'controllers', true),
    $this->baseUrl('/styles/jquery/plugins/rte.css'),
    $this->baseurl('/images/jquery/plugins/rte/')
);
$this->jQuery()->addOnLoad($onload);
?>
<h1><?php echo $title ?></h1>
<div class="span-6">
    <div class="actions">
        <ul class="actions-container">
            <?php
            $param = array('id' => $this->addressId);
            $actions = array(
                'address.action.create' => $param,
                'property.action.show' => $param,
                'property.action.list' => array($this->translate('id') => 1)
            );
            echo $this->partial(
                'navigation/_actions.phtml',
                array(
                    'pages' => $this->actions,
                    'actions' => $actions,
                    'decorator' => 'li'
                )
            )
            ?>
        </ul>
    </div>
</div>
<div class="span-18 last">
    <?php echo $this->addressForm ?>
</div>