<?php
/**
 * Update form for address
 */
?>
<?php
$title = $this->translate('address.action.edit');
$this->headTitle($title);
$this->bundleLink()
     ->appendStylesheet($this->baseUrl('/styles/breadcrumbs.css'), 'screen, projection', false, ['charset' => 'utf-8'])
     ->appendStylesheet($this->baseUrl('/styles/skins/breadcrumbs.css'), 'screen, projection', false, ['charset' => 'utf-8'])
     ->appendStylesheet($this->baseUrl('/styles/forms.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/skins/forms.css'), 'screen, projection', false, ['charset' => 'utf-8'])
     ->appendStylesheet($this->baseUrl('/styles/jquery/plugins/rte.css'), 'screen, projection', false, ['charset' => 'utf-8']);
$this->jQuery()
     ->addJavascriptFile($this->baseUrl('/scripts/jquery/plugins/jquery.validate.js'))
     ->addJavascriptFile($this->baseUrl('/scripts/jquery/plugins/jquery.rte.js'))
     ->addJavascriptFile($this->baseUrl('/scripts/jquery/plugins/jquery.rtetidy.js'))
     ->addJavascriptFile($this->baseUrl('/scripts/jquery/plugins/jquery.confirm.js'))
     ->addJavascriptFile($this->baseUrl('/scripts/jquery/plugins/validate/method.rte.js'))
     ->addJavascriptFile($this->baseUrl('/scripts/edeco/pages/address/class.detail.js'));
$onLoad = sprintf(
    'var page = new Edeco.Pages.Address.Detail();
    page.init("%s", "%s", "%s");',
    $this->url(['controller' => 'city', 'action' => 'search', $this->translate('stateId') => 'stateId'], 'controllers', true),
    $this->baseUrl('/styles/jquery/plugins/rte.css'),
    $this->baseurl('/images/jquery/plugins/rte/')
);
$this->jQuery()->addOnLoad($onLoad);
?>
<h1><?php echo $title ?></h1>
<div class="span-6">
    <div class="actions" id="address-actions">
        <ul class="actions-container">
            <?php
            $params = ['id' => $this->address->id];
            $actions = [
                'address.action.show' => $params,
                'address.action.edit' => $params,
            	'address.action.delete' => $params,
                'property.action.show' => $params,
                'property.action.create' => [],
                'property.action.list' => [$this->translate('page') => 1]
                ] + $this->gMapActions;
            echo $this->partial('navigation/_actions.phtml', [
                'pages' => $this->actions, 'actions' => $actions, 'decorator' => 'li'
            ]);
            ?>
        </ul>
    </div>
</div>
<div class="span-18 last">
    <?php echo $this->addressForm ?>
</div>
