<?php
/**
 * Show property information
 *
 * @author     LMV <luis.montealegre@mandragora-web-systems.com>
 * @copyright  Mandrágora Web-Based Systems 2010
 * @version    SVN: $Id$
 */
?>
<?php
$title = $this->translate('address.action.show');
$this->headTitle($title);
$this->bundleLink()
     ->appendStylesheet($this->baseUrl('/styles/breadcrumbs.css'), 'screen, projection')
     ->appendStylesheet($this->baseUrl('/styles/skins/breadcrumbs.css'), 'screen, projection')
     //Add this styles so that the bundle gets created properly, this actions is conditionally shown in show property
     ->appendStylesheet($this->baseUrl('/styles/forms.css'), 'screen, projection')
     ->appendStylesheet($this->baseUrl('/styles/skins/forms.css'), 'screen, projection')
     ->appendStylesheet($this->baseUrl('/styles/jquery/plugins/rte.css'), 'screen, projection');
//Add this scripts so that the bundle gets created properly, this actions is conditionally shown in show property
$this->jQuery()
     ->addJavascriptFile($this->baseUrl('/scripts/jquery/plugins/jquery.validate.js'))
     ->addJavascriptFile($this->baseUrl('/scripts/jquery/plugins/jquery.rte.js'))
     ->addJavascriptFile($this->baseUrl('/scripts/jquery/plugins/jquery.rtetidy.js'))
     ->addJavascriptFile($this->baseUrl('/scripts/jquery/plugins/jquery.confirm.js'))
     ->addJavascriptFile($this->baseUrl('/scripts/jquery/plugins/validate/method.rte.js'))
     ->addJavascriptFile($this->baseUrl('/scripts/edeco/pages/address/class.show.js'));
$this->jQuery()->addOnLoad(
    'var page = new Edeco.Pages.Address.Show();
    page.init();'
);
?>
<h1><?php echo $title ?></h1>
<div class="span-6">
    <div class="actions" id="address-actions">
        <ul class="actions-container">
            <?php
            $params = array('id' => $this->address->id);
            $actions = array(
                'address.action.edit' => $params,
                'address.action.show' => $params,
            	'address.action.delete' => $params,
                'property.action.list' => array($this->translate('page') => 1),
                'property.action.show' => $params,
            ) + $this->gMapActions;
            echo $this->partial('navigation/_actions.phtml', array('pages' => $this->actions, 'actions' => $actions, 'decorator' => 'li'))
            ?>
        </ul>
    </div>
</div>
<div class="span-18 last">
    <?php echo $this->partial('partials/flash-messages.phtml', array('messages' => $this->messages)) ?>
    <?php echo $this->partial('partials/model.phtml', array('model' => $this->address->toArray(), 'prefix' => 'address.field.')) ?>
</div>