<?php
$this->headTitle('Ayuda');
$this->headTitle('¿Cómo Modificar un mapa de ubicación?');
$this->bundleLink()
     ->appendStylesheet($this->baseUrl('/styles/breadcrumbs.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/skins/breadcrumbs.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/forms.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/skins/forms.css'), 'screen, projection', false, array('charset' => 'utf-8'));
?>
<div class="span-18 prepend-3 clearfix">
    <h1>¿Cómo modificar un mapa de ubicación?</h1>
    <p>Para modificar un mapa de ubicación se deben seguir los siguientes pasos</p>
    <ol>
        <li>
            <p>
                Haga clic en la liga que dice <strong>Inmuebles</strong> en el menú de
                navegación principal como se muestra en la imagen a continuación
            </p>
            <p><img src="<?php echo $this->baseUrl('/images/help/address/create-1.gif') ?>" alt="" /></p>
        </li>
        <li>
            <p>
                El sistema mostrara todos los inmuebles, es necesario dar clic
                sobre la dirección del inmueble como se muestra en la siguiente
                imagen
            </p>
            <p><img src="<?php echo $this->baseUrl('/images/help/address/edit-2.gif') ?>" alt="" /></p>
        </li>
        <li>
            <p>
                Después de hacer clic en la dirección aparecerá la información de
                Mostrar inmueble, Mostrar dirección y Lista de fotografías, la
                información que nos interesa es <strong>Mostara dirección</strong>
            </p>
            <p><img src="<?php echo $this->baseUrl('/images/help/address/edit-3.gif') ?>" alt="" /></p>
        </li>
        <li>
            Y le vamos a dar clic en la liga de <strong>Editar mapa</strong>, ahi
            podemos elegir otro mapa, en el caso de que nos muestren mas opciones,
            o introducir directamente la latitud y la longitud.
        </li>
         <p><img src="<?php echo $this->baseUrl('/images/help/address/edit-4.gif') ?>" alt="" /></p>
    </ol>
</div>