<?php
$this->headTitle('Ayuda');
$this->headTitle('¿Cómo editar los datos de un inmueble?');
$this->bundleLink()
     ->appendStylesheet($this->baseUrl('/styles/breadcrumbs.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/skins/breadcrumbs.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/forms.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/skins/forms.css'), 'screen, projection', false, array('charset' => 'utf-8'));
?>
<div class="span-18 prepend-3 clearfix">
    <h1>¿Cómo editar los datos de un inmueble?</h1>
    <p>Para editar los datos de un inmueble debe seguir los siguientes pasos.</p>
    <ol>
        <li>
            <p>
                Desde la lista de inmuebles debe dar clic en el nombre del inmueble que
                desea modificar (columna con el título Modificar).
            </p>
            <p><img src="<?php echo $this->baseUrl('/images/help/property/edit-1.gif') ?>" alt="" /></p>
        </li>
        <li>
            <p>
                Después de dar clic, verá un formulario casi idéntico al de agregar
                inmueble, el único cambio es el título de la página. Modifique los
                datos necesarios y de clic en el botón de <strong>Guardar</strong>,
                el cual se ubica al final del formulario.
                Vaya a la
                <a href="<?php echo $this->url(array('module' => 'help', 'controller' => 'property', 'action' => 'create'), 'controllers', true)?>">
                    página de ayuda para crear un inmueble
                </a>
                para obtener más detalles de los campos del formulario.
            </p>
            <p><img src="<?php echo $this->baseUrl('/images/help/property/edit-2.gif') ?>" alt="" /></p>
        </li>
    </ol>
</div>