<?php
$this->headTitle('Ayuda');
$this->headTitle('¿Cómo editar los datos de un proyecto?');
$this->bundleLink()
     ->appendStylesheet($this->baseUrl('/styles/breadcrumbs.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/skins/breadcrumbs.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/forms.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/skins/forms.css'), 'screen, projection', false, array('charset' => 'utf-8'));
?>
<div class="span-18 prepend-3 clearfix">
    <h1>¿Cómo editar los datos de un proyecto?</h1>
    <p>Para editar los datos de un proyecto debe seguir los siguientes pasos</p>
    <ol>
        <li>
            <p>
                Desde la lista de proyectos debe dar clic en el botón de
                desea modificar (columna con el título Modificar).
            </p>
            <p><img src="<?php echo $this->baseUrl('/images/help/project/edit-1.gif') ?>" alt="" /></p>
        </li>
        <li>
            <p>
                Después de dar clic,aparecerá el formulario para que modifique
                los datos del proyecto. Vaya a la
                <a href="<?php echo $this->url(array('module' => 'help', 'controller' => 'property', 'action' => 'create'), 'controllers', true)?>">
                    página de ayuda para crear un proyecto
                </a>
                para obtener más detalles.
            </p>
            <p><img src="<?php echo $this->baseUrl('/images/help/project/edit-2.gif') ?>" alt="" /></p>
        </li>
        <li>
            <p>
                Cuando cambien los datos del proyecto de clic en el botón de <strong>Guardar</strong>,
                el cual se ubica al final del formulario. Vaya a la
                <a href="<?php echo $this->url(array('module' => 'help', 'controller' => 'property', 'action' => 'create'), 'controllers', true)?>">
                    página de ayuda para crear un proyecto
                </a>
                para obtener más detalles.
            </p>
            <p><img src="<?php echo $this->baseUrl('/images/help/project/edit-3.gif') ?>" alt="" /></p>
        </li>
        <li>
            <p>
                Usted podrá visualizar los datos del proyecto que ha editado junto
                con la leyenda El proyecto se actualizó correctamente
            </p>
            <p><img src="<?php echo $this->baseUrl('/images/help/project/edit-4.gif') ?>" alt="" /></p>
        </li>
        <li>
            <p>
                Si tienes un archivo PowerPoint con extensión .ppt puede
                únicamente cambiar el nombre del archivo para que tenga la
                extensión .pps y con esto el archivo se reproducirá automáticamente
                al abrirlo o hacer doble clic en el icono.
            </p>
        </li>
    </ol>
</div>