<?php
/**
 * Shows form for creating excel files and the list of available existing files
 *
 * @author     LMV <luis.montealegre@mandragora-web-systems.com>
 * @copyright  Mandrágora Web-Based Systems 2010
 * @version    SVN: $Id$
 */
?>
<?php
$title = $this->translate('excel.action.list');
$this->headTitle($title);
$this->bundleLink()
     ->appendStylesheet($this->baseUrl('/styles/breadcrumbs.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/skins/breadcrumbs.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/forms.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/skins/forms.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/tables.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/skins/tables.css'), 'screen, projection', false, array('charset' => 'utf-8'));
$this->jQuery()
     ->addJavascriptFile($this->baseUrl('/scripts/jquery/plugins/jquery.validate.js'))
     ->addJavascriptFile($this->baseUrl('/scripts/jquery/plugins/jquery.confirm.js'))
     ->addJavascriptFile($this->baseUrl('/scripts/jquery/plugins/validate/method.date-range.js'))
     ->addJavascriptFile($this->baseUrl('/scripts/edeco/pages/excel/class.list.js'));
$this->jQuery()->addOnLoad(
    'var page = new Edeco.Pages.Excel.List();
    page.init();'
);
?>
<h1 class="h1"><?php echo $title ?></h1>
<div class="span-6">
    <div class="actions">
        <ul class="actions-container">
            <?php
            $actions = array(
                'excel.action.create' => array(),
                'excel.action.list' => array($this->translate('page') => 1)
            );
            echo $this->partial(
                'navigation/_actions.phtml',
                array(
                    'pages' => $this->actions,
                    'actions' => $actions,
                    'decorator' => 'li'
                )
            );
            ?>
        </ul>
    </div>
</div>
<div class="span-18 last">
    <?php echo $this->render('partials/flash-messages.phtml') ?>
    <table>
        <colgroup>
            <col width="60" />
            <col width="60" />
            <col width="60" />
            <col width="460" />
        </colgroup>
    <?php if (count($this->excelFiles) == 0) : ?>
        <tr>
            <td colspan="4" class="empty-list">
                <p>Aún no existe ningún archivo de Excel</p>
            </td>
        </tr>
    </table>
    <?php else : ?>
        <tr>
            <th colspan="3">Acciones</th>
            <th>Archivo</th>
        </tr>
        <?php foreach ($this->excelFiles as $file) :?>
            <tr class="<?php echo $this->cycle(array('even', 'odd'))->next() ?>">
                <?php
                $params = array(
                    $this->translate('filename') => $file->getName() . '.xls',
                );
                $actions = array(
                    'excel.action.delete' => $params,
                    'excel.action.show' => $params,
                    'excel.action.download' => $params,
                );
                echo $this->partial(
                    'navigation/_actions.phtml',
                    array(
                        'pages' => $this->actions,
                        'actions' => $actions,
                        'decorator' => 'td'
                    )
                );
                ?>
        	   <td>
        	       <p>
            	       <img src="<?php echo $this->baseUrl('/images/excel.gif')?>"
                            alt="" class="icon" />
        	           <?php echo $file->getNameAndExtension() ?>
            	       <?php echo $file->getSize() ?>
        	       </p>
        	   </td>
        	</tr>
        <?php endforeach ?>
    </table>
    <?php endif ?>
</div>