<?php
/**
 * Show picture information
 *
 * @author     LMV <luis.montealegre@mandragora-web-systems.com>
 * @copyright  Mandrágora Web-Based Systems 2010
 * @version    SVN: $Id$
 */
?>
<?php
$title = $this->translate('excel.action.show');
$this->headTitle($title);
$this->bundleLink()
     ->appendStylesheet($this->baseUrl('/styles/breadcrumbs.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/skins/breadcrumbs.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/tables.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/skins/tables.css'), 'screen, projection', false, array('charset' => 'utf-8'));
$this->jQuery()
     ->addJavascriptFile($this->baseUrl('/scripts/jquery/plugins/jquery.confirm.js'))
     ->addJavascriptFile($this->baseUrl('/scripts/edeco/pages/excel/class.show.js'));
$this->jQuery()->addOnLoad(
    'var page = new Edeco.Pages.Excel.Show();
    page.init();'
);
?>
<h1><?php echo $title ?></h1>
<div class="span-6">
    <div class="actions">
        <ul class="actions-container">
            <?php
            $actions = array(
                'excel.action.create' => array(),
                'excel.action.list' => array(),
                'excel.action.edit' => array($this->translate('filename') => $this->excelFile->filename),
                'excel.action.delete' => array($this->translate('filename') => $this->excelFile->filename),
            );
            echo $this->partial(
                'navigation/_actions.phtml',
                array(
                    'pages' => $this->actions,
                    'actions' => $actions,
                    'decorator' => 'li'
                )
            );
            ?>
        </ul>
    </div>
</div>
<div class="span-18 last">
    <?php echo $this->partial('partials/flash-messages.phtml', array('messages' => $this->messages)) ?>
    <table class="model-show">
        <colgroup>
            <col width="170px" />
            <col width="470px" />
        </colgroup>
        <tr class="even">
            <td class="model-property">
                <?php echo $this->translate('excel.field.startDate') ?>
            </td>
            <td class="model-value">
                <?php echo $this->excelFile->startDate->render() ?>
            </td>
        </tr>
        <tr class="odd">
            <td class="model-property">
                <?php echo $this->translate('excel.field.stopDate') ?>
            </td>
            <td class="model-value">
                <?php echo $this->excelFile->stopDate->render() ?>
            </td>
        </tr>
        <tr class="even">
            <td class="model-property">
                <?php echo $this->translate('excel.action.download') ?>
            </td>
            <td class="model-value">
                <?php
                $params = array(
                    'action' => 'download', 'controller' => 'excel',
                    $this->translate('filename') => $this->excelFile->filename,
                )
                ?>
                <a href="<?php echo $this->url($params, 'controllers', true) ?>" title="<?php echo $this->translate('excel.action.download') ?>" class="action-link">
                    <img alt="<?php echo $this->translate('excel.action.download') ?>" src="/images/action-buttons/download.gif" />
                </a>
            </td>
        </tr>
    </table>
</div>