<?php
/**
 * Shows update property page
 *
 * @author    LMV <luis.montealegre@mandragora-web-systems.com>
 * @copyright Mandrágora Web-Based Systems 2010
 * @version   SVN: $Id$
 */
?>
<?php
$title = $this->translate('property.action.edit');
$this->headTitle($title);
$this->bundleLink()
     ->appendStylesheet($this->baseUrl('/styles/breadcrumbs.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/skins/breadcrumbs.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/forms.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/skins/forms.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/jquery/plugins/rte.css'), 'screen, projection', false, array('charset' => 'utf-8'));
$this->jQuery()
     ->addJavascriptFile($this->baseUrl('/scripts/jquery/plugins/jquery.rte.js'))
     ->addJavascriptFile($this->baseUrl('/scripts/jquery/plugins/jquery.rtetidy.js'))
     ->addJavascriptFile($this->baseUrl('/scripts/jquery/plugins/jquery.validate.js'))
     ->addJavascriptFile($this->baseUrl('/scripts/jquery/plugins/jquery.confirm.js'))
     ->addJavascriptFile($this->baseUrl('/scripts/jquery/plugins/jquery.maskedinput-1.2.2.min.js'))
     ->addJavascriptFile($this->baseUrl('/scripts/jquery/plugins/validate/method.rte.js'))
     ->addJavascriptFile($this->baseUrl('/scripts/edeco/pages/property/class.detail.js'));
$onLoad = sprintf(
    'var page = new Edeco.Pages.Property.Detail();
    page.init("%s", "%s");',
    $this->baseUrl('/styles/jquery/plugins/rte.css'),
    $this->baseurl('/images/jquery/plugins/rte/')
);
$this->jQuery()->addOnLoad($onLoad);
?>
<h1><?php echo $title ?></h1>
<div class="span-6">
    <div class="actions">
        <ul class="actions-container">
            <?php
            $params = array('id' => $this->property->id);
            $actions = array(
                'property.action.list' => array($this->translate('page') => 1),
                'property.action.create' => $params,
                'property.action.edit' => $params,
                'property.action.show' => $params,
                'property.action.delete' => $params,
            );
            echo $this->partial(
                'navigation/_actions.phtml',
                array(
                    'pages' => $this->actions,
                    'actions' => $actions,
                    'decorator' => 'li'
                )
            );
            ?>
        </ul>
    </div>
</div>
<div class="span-18 last">
    <?php echo $this->propertyForm ?>
</div>