<?php
/**
 * Show property information
 *
 * @author     LMV <luis.montealegre@mandragora-web-systems.com>
 * @copyright  Mandrágora Web-Based Systems 2010
 * @version    SVN: $Id$
 */
?>
<?php
$title = $this->translate('property.action.show');
$this->headTitle($title);
$this->bundleLink()
     ->appendStylesheet($this->baseUrl('/styles/breadcrumbs.css'), 'screen, projection')
     ->appendStylesheet($this->baseUrl('/styles/skins/breadcrumbs.css'), 'screen, projection')
     ->appendStylesheet($this->baseUrl('/styles/tables.css'), 'screen, projection')
     ->appendStylesheet($this->baseUrl('/styles/skins/tables.css'), 'screen, projection');
$this->jQuery()
     ->addJavascriptFile($this->baseUrl('/scripts/jquery/plugins/jquery.confirm.js'))
     ->addJavascriptFile($this->baseUrl('/scripts/edeco/pages/address/class.show.js'))
     ->addJavascriptFile($this->baseUrl('/scripts/edeco/pages/address/class.detail.js'))
     ->addJavascriptFile($this->baseUrl('/scripts/edeco/pages/property/class.show.js'));
$this->jQuery()->addOnLoad(
    'var propertyPage = new Edeco.Pages.Property.Show();
    propertyPage.init();'
);
?>
<h1><?php echo $this->translate('property.action.show') ?></h1>
<div class="clearfix">
    <div class="span-6">
        <div class="actions">
            <ul class="actions-container" id="actions-property">
                <?php
                $params = array('id' => $this->property->id);
                $listParams = array($this->translate('page') => 1);
                $pictureParams = array($this->translate('propertyId') => $this->property->id);
                $actions = array(
                    'property.action.list' => $listParams,
                    'property.action.create' => array(),
                    'property.action.edit' => $params,
                    'property.action.show' => $params,
                    'property.action.delete' => $params,
                    'address.action.create' => $params,
                	'address.action.show' => $params,
                	'picture.action.list' => $pictureParams + $listParams,
                	'recommendedProperty.action.list' => $pictureParams + array($this->translate('stateId') => $this->stateId) + $listParams,
                );
                echo $this->partial(
                    'navigation/_actions.phtml',
                    array(
                        'pages' => $this->actions,
                        'actions' => $actions,
                        'decorator' => 'li'
                    )
                );
                ?>
            </ul>
        </div>
    </div>
    <div class="span-18 last">
        <?php echo $this->partial('partials/flash-messages.phtml', array('messages' => $this->messages)) ?>
        <?php echo $this->partial('partials/model.phtml', array('model' => $this->property->toArray(), 'prefix' => 'property.field.')) ?>
    </div>
</div>