<?php
$this->headTitle('Ayuda');
$this->headTitle('¿Cómo crear un usuario?');
$this->bundleLink()
     ->appendStylesheet($this->baseUrl('/styles/breadcrumbs.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/skins/breadcrumbs.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/forms.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/skins/forms.css'), 'screen, projection', false, array('charset' => 'utf-8'));
?>
<div class="span-18 prepend-3 clearfix">
    <h1>¿Cómo crear un usuario?</h1>
    <p>Para crear un usuario debe seguir los siguientes pasos</p>
    <ol>
        <li>
            <p>
                En el menú de la página haga clic en la liga que dice <strong>Usuario</strong>
                en el menú de navegación principal como se muestra en la imagen a continuación
            </p>
            <p><img src="<?php echo $this->baseUrl('/images/help/user/create-1.gif') ?>" alt="" /></p>
        </li>
        <li>
            <p>
                Después verá una liga que dice <strong>Crear usuario</strong>,
                como se muestra en la siguiente imagen.
            </p>
            <p><img src="<?php echo $this->baseUrl('/images/help/user/create-2.gif') ?>" alt="" /></p>
        </li>
        <li>
            <p>
                Después de hacer clic en Crear usuario aparecerá el formulario para que
                ingrese los datos del usuario.
            </p>
            <p><img src="<?php echo $this->baseUrl('/images/help/user/create-3.gif') ?>" alt="" /></p>
        </li>
        <li>
            <p>
                El campo <strong>Nombre de usuario</strong> es donde ingresa la dirección de
                correo electrónico del nuevo usuario, como se muestra en la siguiente imagen.
            </p>
            <p><img src="<?php echo $this->baseUrl('/images/help/user/create-4.gif') ?>" alt="" /></p>
        </li>
        <li>
            <p>
                Cuando haya capturado toda la información obligatoria de clic en
                <strong>Guardar</strong>.
                Después de guardar, la aplicación volverá a la lista de usuarios.
            </p>
        </li>
    </ol>
</div>