<?php
/**
 * Partial for show action
 */
?>
<table class="model-show">
    <colgroup>
        <col width="170px" />
        <col width="470px" />
    </colgroup>
    <?php $property = new \Mandragora\StringObject('') ?>
    <?php foreach ($this->model as $attribute => $value ) : ?>
        <?php $property->setValue($attribute) ?>
    	<?php if (!is_null($value) && $attribute != 'id' && $attribute != 'version' && $attribute != 'active' && !$property->endsWith('Id')) : ?>
            <tr class="<?php echo $this->cycle(array('even', 'odd'))->next() ?>">
                <td class="model-property"><?php echo $this->translate($this->prefix . $attribute) ?></td>
                <?php if ($value instanceof \Mandragora\Model\Property\PropertyInterface) : ?>
                    <td class="model-value"><?php echo $this->translate($value->render()) ?></td>
                <?php else : ?>
                    <td class="model-value"><?php echo $this->translate($value) ?></td>
                <?php endif ?>
            </tr>
        <?php endif ?>
    <?php endforeach ?>
</table>