<?php
/**
 * Branding section
 *
 * @author     LMV <luis.montealegre@mandragora-web-systems.com>
 * @copyright  Mandrágora Web-Based Systems 2010
 * @version    SVN: $Id$
 */
?>
<a href="<?php echo $this->baseUrl('/') ?>" class="logo" accesskey="0"
   title="Edificaciones y Desarrollos Comerciales de México">
   <img src="<?php echo $this->baseUrl('/images/logo-edeco.gif') ?>"
        alt="EDECO, Edificaciones y Desarrollos Comerciales de México" />
</a>