<p class="footer-p">
    &copy; EDECO <?php echo $this->copyrightYear() ?>.
    Todos los derechos reservados.
</p>
<?php
echo $this->headScript();
$moduleName = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();
if ($moduleName === 'admin' || $this->bundleScript()->isEnabled()) {
    $this->bundleScript()->enable()->uiEnable()
         ->setLocalPath($this->baseUrl('/scripts/jquery/jquery-1.6.2.min.js'))
         ->setUiLocalPath($this->baseUrl('/scripts/jquery/jquery-ui-1.8.14.custom.min.js'));
    echo $this->bundleScript(true);
}
?>
