<?php
/**
 * Helper for form elements, except for buttons and the form itself.
 *
 * This helper is used with Mandragora_Form_Abstract class
 *
 * @author    LMV <luis.montealegre@mandragora-web-systems.com>
 * @version   SVN $Id$
 * @copyright Mandrágora Web-Based Systems 2010
 */
?>
<?php
$label = $this->element->getLabel();
if ($label != '') {
    if ($this->element->isRequired()) {
        $acronym = '<acronym class="required" title="Obligatorio">*</acronym>';
        $label = $this->escape($label) . ' ' . $acronym;
    }
    echo $this->formLabel(
        $this->element->getName(), $label, array('escape' => false)
    );
}
?>
<?php
$attribs = $this->element->getAttribs();
unset($attribs['helper']);
$helper = $this->element->helper;
$multiOptions = null;
if ($this->element instanceof Zend_Form_Element_Multi) {
    $multiOptions = $this->element->getMultiOptions();
}
echo $this->element->getView()->$helper(
    $this->element->getName(), $this->element->getValue(), $attribs,
    $multiOptions
);
?>
<?php if (count($this->element->getMessages()) > 0) : ?>
    <div class="error">
        <ul>
        <?php $errorMessages = $this->element->getMessages() ?>
        <?php foreach ($errorMessages as $error) : ?>
            <li><?php echo $this->escape($error) ?></li>
        <?php endforeach ?>
        </ul>
    </div>
<?php endif ?>
<?php if ($this->element->getDescription()) : ?>
    <div class="hint">
        <?php echo $this->element->getDescription() ?>
    </div>
<?php endif ?>