<?php
/**
 * Shows list of all active categories
 *
 * @author     LMV <luis.montealegre@mandragora-web-systems.com>
 * @copyright  Mandrágora Web-Based Systems 2010
 * @version    SVN: $Id$
 */
?>
<?php
$title = $this->translate('category.action.list');
$this->headTitle($title);
$this->bundleLink()
     ->appendStylesheet($this->baseUrl('/styles/forms.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/skins/forms.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/inline-forms.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/breadcrumbs.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/skins/breadcrumbs.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/tables.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/skins/tables.css'), 'screen, projection', false, array('charset' => 'utf-8'));
$this->jQuery()
     ->addJavascriptFile($this->baseUrl('/scripts/jquery/plugins/jquery.confirm.js'))
     ->addJavascriptFile($this->baseUrl('/scripts/edeco/pages/property/class.list.js'));
$this->jQuery()->addOnLoad(
    'var page = new Edeco.Pages.Category.List();
    page.init();'
);
?>
<h1><?php echo $title ?></h1>
<div class="span-6">
    <div class="actions">
        <ul class="actions-container">
            <?php $params = array($this->translate('page') => 1) ?>
            <?php $actions = array('category.action.list' => $params, 'category.action.create' => array()) ?>
            <?php echo $this->partial('navigation/_actions.phtml', array('pages' => $this->actions, 'actions' => $actions, 'decorator' => 'li')) ?>
        </ul>
    </div>
</div>
<div class="span-18 last">
    <?php echo $this->render('partials/flash-messages.phtml') ?>
    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'partials/paginator.phtml') ?>
    <table>
        <colgroup>
            <col width="60" />
            <col width="60" />
            <col width="60" />
            <col width="460" />
        </colgroup>
    <?php if ($this->collection->count() == 0) : ?>
        <tr>
            <td colspan="4" class="empty-list">
                <p>Aún no existe ninguna categoría</p>
            </td>
        </tr>
    </table>
    <?php else : ?>
        <tr>
            <th colspan="3">Acciones</th>
            <th>Descripción</th>
        </tr>
        <?php foreach ($this->collection as $category) : ?>
            <tr class="<?php echo $this->cycle(array('even', 'odd'))->next() ?>">
                <?php $params = array('id' => $category->id) ?>
                <?php $actions = array('category.action.delete' => $params, 'category.action.edit' => $params, 'category.action.show' => $params) ?>
                <?php echo $this->partial('navigation/_actions.phtml', array('pages' => $this->actions, 'actions' => $actions, 'decorator' => 'td',)) ?>
                <td><p><?php echo $category ?></p></td>
            </tr>
        <?php endforeach ?>
        </table>
    <?php endif ?>
    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'partials/paginator.phtml') ?>
</div>