<?php
/**
 * Shows the google map results and the form to store the latitude and
 * longitude for the selected map
 *
 * @author     LMV <luis.montealegre@mandragora-web-systems.com>
 * @copyright  Mandrágora Web-Based Systems 2010
 * @version    SVN: $Id$
 */
?>
<?php
$title = $this->title;
$this->headTitle($title);
$this->bundleLink()
     ->appendStylesheet($this->baseUrl('/styles/breadcrumbs.css'), 'screen, projection')
     ->appendStylesheet($this->baseUrl('/styles/skins/breadcrumbs.css'), 'screen, projection')
     ->appendStylesheet($this->baseUrl('/styles/forms.css'), 'screen, projection')
     ->appendStylesheet($this->baseUrl('/styles/skins/forms.css'), 'screen, projection')
     ->appendStylesheet($this->baseUrl('/styles/tables.css'), 'screen, projection')
     ->appendStylesheet($this->baseUrl('/styles/skins/tables.css'), 'screen, projection');
$googleMapUrl = sprintf('http://maps.google.com/maps?file=api&v=2&key=%s&sensor=false', $this->googleMapsKey);
$this->headScript()->appendFile($googleMapUrl);
$this->jQuery()
     ->addJavascriptFile($this->baseUrl('/scripts/jquery/plugins/jquery.map.js'))
     ->addJavascriptFile($this->baseUrl('/scripts/jquery/plugins/jquery.validate.js'))
     ->addJavascriptFile($this->baseUrl('/scripts/edeco/pages/google-map/class.detail.js'));
$onload = sprintf(
    'var page = new Edeco.Pages.GoogleMap.Detail();
    page.init(%s);',
    $this->jsonPlaceMarkers
);
$this->jQuery()->addOnLoad($onload);
?>
<h1><?php echo $title ?></h1>
<div class="span-6">
    <div class="actions">
        <ul class="actions-container">
            <?php
            $params = array('id' => $this->addressId);
            $actions = array(
                'address.action.show' => $params,
                'address.action.edit' => $params,
                'property.action.show' => $params,
                'property.action.list' => array($this->translate('page') => 1)
            ) + $this->gMapActions;
            echo $this->partial(
                'navigation/_actions.phtml',
                array('pages' => $this->actions, 'actions' => $actions, 'decorator' => 'li')
            );
            ?>
        </ul>
    </div>
</div>
<div class="span-18 last">
    <table>
    <colgroup>
        <col width="200" />
        <col width="350" />
        <col width="70" />
    </colgroup>
    <?php if (count($this->placeMarks) == 0) : ?>
        <tr>
            <td colspan="3" class="empty-list">
                <p>No se encontro ninguna dirección</p>
            </td>
        </tr>
    </table>
    <?php  else : ?>
        <tr>
            <th>Dirección</th>
            <th>Mapa</th>
            <th>Seleccionar</th>
        </tr>
        <?php $i = 0;?>
        <?php $addressAccuracy = App_Enum_AddressAccuracy::values() ?>
        <?php foreach ($this->placeMarks as $placemark) : ?>
            <tr class="<?php echo $this->cycle(array('even', 'odd'))->next() ?>">
                <td>
                    <p>
                        <?php echo $placemark->getAddress() ?> <br />
                        <strong>Latitud:</strong>
                        <?php echo $placemark->getPoint()->getLatitude() ?> <br />
                        <strong>Longitud:</strong>
                        <?php echo $placemark->getPoint()->getLongitude() ?> <br />
                        <strong>Exactitud:</strong>
                        <?php echo $addressAccuracy[$placemark->getAccuracy()] ?> <br />
                        <input type="hidden"  id="latitude-<?php echo $i;?>"
                               value="<?php echo $placemark->getPoint()->getLatitude()?>"/>
                        <input type="hidden" id="longitude-<?php echo $i;?>"
                               value="<?php echo $placemark->getPoint()->getLongitude()?>"/>
                   </p>
                </td>
                <td>
                    <div id="google-map-<?php echo $i ?>"
                         style="width: 350px; height: 280px;">
                    </div>
                </td>
                <td>
                    <input type="checkbox" id="<?php echo $i ?>" />
                </td>
            </tr>
            <?php $i++ ?>
        <?php endforeach ?>
    </table>
    <?php endif ?>
    <?php echo $this->googleForm ?>
</div>