<?php
/**
 * Shows list of all active projects
 *
 * @author     LMV <luis.montealegre@mandragora-web-systems.com>
 * @author     LNJ <lemuel.nonoal@mandragora-web-systems.com>
 * @copyright  Mandrágora Web-Based Systems 2010
 * @version    SVN: $Id$
 */
?>
<?php
$title =  $this->translate('project.action.list');
$this->headTitle($title);
$this->bundleLink()
     ->appendStylesheet($this->baseUrl('/styles/breadcrumbs.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/skins/breadcrumbs.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/forms.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/skins/forms.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/inline-forms.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/tables.css'), 'screen, projection', false, array('charset' => 'utf-8'))
     ->appendStylesheet($this->baseUrl('/styles/skins/tables.css'), 'screen, projection', false, array('charset' => 'utf-8'));
$this->jQuery()
     ->addJavascriptFile($this->baseUrl('/scripts/jquery/plugins/jquery.confirm.js'))
     ->addJavascriptFile($this->baseUrl('/scripts/edeco/pages/project/class.list.js'));
$this->jQuery()->addOnLoad(
    'var page = new Edeco.Pages.Project.List();
    page.init();'
);
?>
<h1 class="h1"><?php echo $title ?></h1>
<div class="span-6">
    <div class="actions">
        <ul class="actions-container">
            <?php
            $params = array($this->translate('page') => 1);
            $actions = array('project.action.list' => $params,);
            if ($this->role == 'admin') {
                $actions += array('project.action.create' => array());
            }
            echo $this->partial(
                'navigation/_actions.phtml',
                array(
                    'pages' => $this->actions,
                    'actions' => $actions,
                    'decorator' => 'li'
                )
            );
            ?>
        </ul>
    </div>
</div>
<div class="span-18 last">
    <?php echo $this->render('partials/flash-messages.phtml') ?>
    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'partials/paginator.phtml') ?>
    <table>
        <colgroup>
            <?php if ($this->role == 'admin') : ?>
                <col width="60" />
                <col width="60" />
                <col width="60" />
                <col width="460" />
            <?php else : ?>
                <col width="60" />
                <col width="580" />
            <?php endif ?>
        </colgroup>
    <?php if ($this->projects->count() == 0) : ?>
        <tr>
            <?php $colspan = $this->role == 'admin' ? 4 : 2; ?>
            <td colspan="<?php echo $colspan?>" class="empty-list">
                <p> Aún no existe ningun proyecto de inversión </p>
            </td>
        </tr>
    </table>
    <?php else : ?>
        <tr>
            <?php if ($this->role == 'admin') : ?>
                <th colspan="3">Acciones</th>
                <th>Descripción</th>
            <?php else : ?>
                <th>Acciones</th>
                <th>Descripción</th>
            <?php endif ?>
        </tr>
        <?php foreach ($this->projects as $project) : ?>
            <tr class="<?php echo $this->cycle(array('even', 'odd'))->next() ?>">
                <?php
                $params = array('id' => $project->id);
                $actions = array(
                    'project.action.show' => $params,
                );
                if ($this->role == 'admin') {
                    $actions += array(
                        'project.action.delete' => $params,
                        'project.action.edit' => $params,
                    );
                }
                echo $this->partial(
                    'navigation/_actions.phtml',
                    array(
                        'pages' => $this->actions,
                        'actions' => $actions,
                        'decorator' => 'td',
                    )
                );
                ?>
                <td><p><?php echo $project ?></p></td>
            </tr>
        <?php endforeach ?>
        </table>
    <?php endif ?>
    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'partials/paginator.phtml') ?>
</div>